/**
 * Generated by Bridge.NET 15.3.0
 */

Bridge.assembly({
        name: "TestProject",
        compiler: "15.3.0"
    },
    function ($asm, globals) {
        "use strict";

        Bridge.define("Test.BridgeIssues.N065.Class65_1");

        Bridge.define("Test.BridgeIssues.N065.Class65_1.Nested");

        Bridge.define("Test.BridgeIssues.N065.Class65_2", {
            inherits: [Test.BridgeIssues.N065.Class65_1.Nested]
        });
    }
);
