/**
 * Generated by Bridge.NET 15.3.0
 */

Bridge.assembly({
        name: "TestProject",
        compiler: "15.3.0"
    },
    function ($asm, globals) {
        "use strict";

        Bridge.define("Test.BridgeIssues.N059.Class59", {
            statics: {
                method1: function () {
                }
            },
            method1: function (d) {
            }
        });

        Bridge.define("Test.BridgeIssues.N059.Class59.Aux1");
    }
);
