/**
 * Generated by Bridge.NET 15.3.0
 */

Bridge.assembly({
        name: "TestProject",
        compiler: "15.3.0"
    },
    function ($asm, globals) {
        "use strict";

        
        Bridge.define("Test.BridgeIssues.N856.Bridge856", {
            statics: {
                
                test1: function () {
                }
            },
            config: {
                properties: {
                    
                    
                    TestProperty: 0
                }
            },
            
            test2: function (a) {
                if (a === void 0) { a = null; }

            }
        });
    }
);
