/**
 * Generated by Bridge.NET 15.3.0
 */

/* 
    A custom comment
*/

Bridge.assembly({
        name: "TestProject",
        compiler: "15.3.0"
    },
    function ($asm, globals) {
        "use strict";

        Bridge.define("Test.BridgeIssues.N1009.Class1009", {
            statics: {

            }
        });
    }
);

/* 
    A custom comment
*/
