/**
 * Generated by Bridge.NET 15.3.0
 */

Bridge.assembly({
        name: "TestProject",
        compiler: "15.3.0"
    },
    function ($asm, globals) {
        "use strict";

        Bridge.define("Test.BridgeIssues.N557.Bridge557", {
            statics: {
                test1: function () {
                    var text = document.createTextNode('');
                },
                test2: function () {
                    var text = document.createTextNode("Some text");
                }
            }
        });
    }
);
