/**
 * Generated by Bridge.NET 15.3.0
 */

Bridge.assembly({
        name: "TestProject",
        version: "1.0.0-beta",
        compiler: "15.3.0"
    },
    function ($asm, globals) {
        "use strict";

        Bridge.define("TestProject.Issues.JustClass");
    }
);
